### ISSUE TITLE
Resetting form with <kendo-dropdownlist> with object values throws Exception

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular2#76] opened 2016-11-03 13:39 UTC
Hello,

I'm trying to reset form which contains <kendo-dropdownlist> with complex (object) values.
I get this exception:

> Expected initial value of type Object. See http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/#value-selection

### Example:
```
<form #form="ngForm">
  <kendo-dropdownlist [data]="listItems" 
    [(ngModel)]="item0" 
    name="item0" 
    textField="l"
    valueField="v"></kendo-dropdownlist>
</form>
<button (click)="form.resetForm()">Clear</button>
```
and here's the data:
```
public listItems: Array<Object> = [
      {l: "Item 1", v: 1},
      {l: "Item 2", v: 2},
      {l: "Item 3", v: 3},
      {l: "Item 4", v: 4},
    ];
```

### Plunker
http://plnkr.co/edit/gYRX0Y?p=preview

**Comment by valchev** [comment] 2016-11-14 16:51
Thank you for the report.
The issue is fixed in the latest version.

**Closed by valchev** 2016-11-14 16:51 UTC
Labels: bug

**Comment by NguyenDo-Consulting** [comment] 2016-12-23 06:19
I'm getting a similar exception but with combobox

Expected initial value of type Object. See http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/#toc-value-selection

**Comment by valchev** [comment] 2016-12-23 14:34
@NguyenDo-Consulting I was not able to reproduce the issue in the example from the link that you provided.

Could you please provide a test page so I can examine it?
