### ISSUE TITLE
Kendo DropDownList- random crash when switching tabs

### ISSUE THREAD

**Issue by PierLucSimard** [telerik/kendo-angular2#29] opened 2016-09-28 08:53 UTC
Im using Kendo DropDownList in a tab control and sometimes (20% of the time) there is this exception in the console when I change the tab and try to comeback to the orignal tab.

![image](https://cloud.githubusercontent.com/assets/22493500/18906885/655e7f36-8537-11e6-8ee4-e023912aa04d.png)

  this.ddlDataSource = [
      { Id: 1, Display: "2016/9/28 - 2016/10/14" },
      { Id: 2, Display: "2016/10/14 - 2016/10/31" },
      { Id: 3, Display: "2016/11/01 - 2016/11/14" },
      { Id: 4, Display: "2016/11/28 - 2016/12/14" },
      { Id: 5, Display: "2016/9/28 - 2016/10/14" },
      { Id: 6, Display: "2016/10/14 - 2016/10/31" },
      { Id: 7, Display: "2016/11/01 - 2016/11/14" },
      { Id: 8, Display: "2016/11/28 - 2016/12/14" },
      { Id: 9, Display: "2016/9/28 - 2016/10/14" },
      { Id: 10, Display: "2016/10/14 - 2016/10/31" },
      { Id: 11, Display: "2016/11/01 - 2016/11/14" },
      { Id: 12, Display: "2016/11/28 - 2016/12/14" },
      { Id: 13, Display: "2016/9/28 - 2016/10/14" },
      { Id: 14, Display: "2016/10/14 - 2016/10/31" },
      { Id: 15, Display: "2016/11/01 - 2016/11/14" },
      { Id: 16, Display: "2016/11/28 - 2016/12/14" }];

core.umd.js:3462 EXCEPTION: Error in ./DropDownListComponent class DropDownListComponent - inline template:18:93 caused by: Expression has changed after it was checked. Previous value: '300px'. Current value: '0px'.ErrorHandler.handleError @ core.umd.js:3462
core.umd.js:3464 ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: '300px'. Current value: '0px'.ErrorHandler.handleError @ core.umd.js:3464
core.umd.js:3467 ORIGINAL STACKTRACE:ErrorHandler.handleError @ core.umd.js:3467
core.umd.js:3468 Error: Expression has changed after it was checked. Previous value: '300px'. Current value: '0px'.
    at ExpressionChangedAfterItHasBeenCheckedError.Error (native)
    at ExpressionChangedAfterItHasBeenCheckedError.BaseError [as constructor] (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:1255:38)
    at new ExpressionChangedAfterItHasBeenCheckedError (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:5545:20)
    at checkBinding (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:5689:23)
    at DebugAppView._View_DropDownListComponent4.detectChangesInternal (DropDownListComponent.ngfactory.js:714:7)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9566:18)
    at DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9671:48)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9584:23)
    at DebugAppView._View_DropDownListComponent0.detectChangesInternal (DropDownListComponent.ngfactory.js:228:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9566:18)ErrorHandler.handleError @ core.umd.js:3468
core.umd.js:3471 ERROR CONTEXT:ErrorHandler.handleError @ core.umd.js:3471
core.umd.js:3472 DebugContextErrorHandler.handleError @ core.umd.js:3472
zone.js:140 Uncaught Error: Error in ./DropDownListComponent class DropDownListComponent - inline template:18:93 caused by: Expression has changed after it was checked. Previous value: '300px'. Current value: '0px'.

![image](https://cloud.githubusercontent.com/assets/22493500/18906713/a9c8e252-8536-11e6-809c-07e2724ab797.png)

**Comment by ggkrustev** [comment] 2016-09-28 08:56
Hi @PierLucSimard,
it seems that the issue is related to components automatic popup resize. I assume that Angular detects changes after checked has been done, which is unexpected.

Could you provide more details about the component setup that uses the DropDownList? A runnable demo will be of a great help.

**Comment by PierLucSimard** [comment] 2016-09-28 09:29
https://plnkr.co/edit/LEpgaP?p=preview

It happens when the Ddl popup is **open** and u switch tab. all my tabs use ng-if

![image](https://cloud.githubusercontent.com/assets/22493500/18908143/7a8c3b00-853c-11e6-9f0f-0451425ffd1e.png)

![image](https://cloud.githubusercontent.com/assets/22493500/18908095/45d7ed0a-853c-11e6-9901-e916617e61bb.png)

**Comment by PierLucSimard** [comment] 2016-09-28 09:36
After more testing in my project the problem seem to be related also (just like the DDL problem) to using the grid inside a tab control with:

<div *ngIf="active">
    <ng-content></ng-content>
</div>

**Comment by PierLucSimard** [comment] 2016-09-28 12:12
I will try to create the project tonigh,

**Comment by PierLucSimard** [comment] 2016-09-28 21:20
http://plnkr.co/edit/QTzrf15Le2npmBqMgmlf?p=preview

This exemple reproduce the issue. Just open the ddl popup (dont close) and switch tab. Check in the console.

**Comment by ggkrustev** [comment] 2016-09-29 15:40
Thank you for the repro demo. Indeed, the Angular will detect unexpected property change when tabs are switched. 

Long story short, it seems that the components are still live when tabs are switched, hence the dropdownlist will try to update some of its internal properties and thus will change the state.
I logged the issue in DropDowns repo:
- https://github.com/telerik/kendo-angular-dropdowns/issues/8

I will post an update once the issue is resolved.

**Comment by ggkrustev** [comment] 2016-09-30 14:40
I will close the issue for now. Please post an update if the problem still persists

**Closed by ggkrustev** 2016-09-30 14:40 UTC
