### ISSUE TITLE
Dialog styling Problems with addional Elements on Page

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular2#156] opened 2017-01-02 08:30 UTC
when you use bootstrap in your application with the dialog

      <div class="row">
      <button kendoButton *ngIf="!opened" (click)="open()">Open dialog</button>
      <kendo-dialog title="Action required" *ngIf="opened" (close)="close('cancel')">
          <p>Entropy happened.</p>
          <p>Do you accept?</p>
          <kendo-dialog-actions>
              <button kendoButton (click)="close('yes')" primary="true">Yes</button>
              <button kendoButton (click)="close('no')">No</button>
          </kendo-dialog-actions>
      </kendo-dialog>
      </div>
      <div class="row">
         <div class="col-md-12>
          <a class="btn btn-default btn-primary btn-block">TEST BUTTON</a>
         </div>
      </div>
      

http://plnkr.co/edit/MIjmsWlSf2KFjAV915Wf?p=preview

then the overlay is not "blocking" the bootstrap items like buttons

![unbenannt](https://cloud.githubusercontent.com/assets/1572878/21586139/8e3f81de-d0cd-11e6-8d16-fbc0d2d52388.png)

**Comment by gyoshev** [comment] 2017-01-02 12:43
Closed in v1.33.3 via telerik/kendo-theme-default@bc210f0bb2cce

Duplicate of #153

**Closed by gyoshev** 2017-01-02 12:43 UTC
