### ISSUE TITLE
Tooltips far away from select point

### ISSUE THREAD

**Issue by Cabeda** [telerik/kendo-angular2#98] opened 2016-11-23 16:05 UTC
I'm using tooltips on my charts but they don't appear near the selected data point. 

I'm using the following configuration (which doesn't have anything special) with the version 0.8.1:

`<kendo-chart-series-item-tooltip [visible]="true" format="Series 1 value: {0}">
</kendo-chart-series-item-tooltip>`

**Comment by tsvetomir** [comment] 2016-11-23 18:00
I'm testing this [here](http://plnkr.co/edit/cXiqp8NmLXh8faZyQpMO?p=preview) with the latest published release.

* Can you modify the snippet to reproduce the issue?
* Is the issue unique to a Browser / OS combination?

**Comment by Cabeda** [comment] 2016-11-24 12:32
I've create a fork [here](http://plnkr.co/edit/gOnmKL?p=preview). 

It's not exactly like I have in my code but I've tried to reproduce the best I could. I set multiple panes but the tooltip doesn't stay near in the last panes.

**Comment by tsvetomir** [comment] 2016-12-01 15:41
I couldn't reproduce the issue initially, but upon revisiting I've got this:

![image](https://cloud.githubusercontent.com/assets/247917/20800190/50e33cfc-b7ed-11e6-8926-0d60f8acbb13.png)

Is it the same as the problem you're experiencing?

**Comment by Cabeda** [comment] 2016-12-01 15:55
Almost, in my case the tooltip stays always at the top right of the window and when moving to another point (no matter the pane) it only moves horizontally

**Comment by ggkrustev** [comment] 2016-12-02 09:46
The tooltip positioning seems to be related to a bug in the Popup component. Check this thread for a resolution:

https://github.com/telerik/kendo-angular2/issues/115

**Comment by ggkrustev** [comment] 2016-12-06 10:20
### UPDATE
It turned out that the issue has already been fixed. The plunker just uses an older Popup version. The latest official Popup version is v0.14.2.

I will close the issue for now. Comment if the issue still persists with the mentioned Popup version.

**Closed by ggkrustev** 2016-12-06 10:20 UTC
