### ISSUE TITLE
Kendo Dropdown with Bootstrap 3.3.x 

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular2#142] opened 2016-12-19 09:20 UTC
Hi,

I try to use for default theming (Panels, Grid, ...) Bootstrap 3.3.x with less and only want to use the Default Kendo Ui Styles.

but when I just import the bootstrap Styles the dropdownlists look like this:

![unbenannt](https://cloud.githubusercontent.com/assets/1572878/21307139/80ab6082-c5d4-11e6-98b1-63205ad26b3b.png)

a Plunkr with the descriped problem can be founde here:

http://plnkr.co/edit/3IdecM4wAXgoJUH1JEws?p=preview

**Comment by gyoshev** [comment] 2016-12-19 15:10
Thanks for reporting this! The problem is caused by the `box-sizing` of the dropdowns -- Bootstrap adds `box-sizing: border-box` to all elements, and the dropdowns expect `content-box`. We have [committed to fix such problems](https://github.com/telerik/kendo-angular2/issues/19#issuecomment-247758522) when they occur, so that themes are compatible with both `box-sizing` values. The bug will be addressed within the theme shortly.

**Closed** 2016-12-27 09:10 UTC
Labels: bug, styling
