### ISSUE TITLE
Can't import GridModule with Angular 2.0.1

### ISSUE THREAD

**Issue by fgladisch** [telerik/kendo-angular2#27] opened 2016-09-27 08:53 UTC
Hi,

after upgrading to Angular 2.0.1 from Angular 2.0.0, the following error is thrown in the browser by the Angular compiler when GridModule is imported:

`Uncaught Error: Unexpected value 'GridModule' imported by the module 'AppModule'`

My dependencies:

```
...
  "dependencies": {
    "@angular/common": "2.0.1",
    "@angular/compiler": "2.0.1",
    "@angular/core": "2.0.1",
    "@angular/forms": "2.0.1",
    "@angular/http": "2.0.1",
    "@angular/platform-browser": "2.0.1",
    "@angular/platform-browser-dynamic": "2.0.1",
    "@angular/router": "3.0.1",
    "@progress/kendo-angular-grid": "0.3.2"
  }
...
```

Any ideas?

**Comment by rkonstantinov** [comment] 2016-09-27 10:19
The cause for the error is that the current version of the Grid package (similar to the other kendo-angular-* packages) depends on Angular package exact version (2.0.0). And it will not work with other versions as this will result in loading multiple versions of Angular and the error in question.

Maybe we should release a bit more the dependencies versioning schema and allow patch versions updates of the Angular packages. @underlog, @tsvetomir what do you think?

**Comment by fgladisch** [comment] 2016-09-27 11:33
After posting this issue I also noticed the dependencies of kendo-angular-grid to Angular 2.0.0. I guess I expected that minor versions wouldn't affect the compatibility, since no Angular APIs changed. I agree that a dependency to something like Angular 2.0.* would be more useful for the future.

On the other hand: Why hasn't my dependency to [ng2-translate](https://github.com/ocombe/ng2-translate) (which also requires Angular 2.0.0) not resulted in the same issue?

**Comment by ggkrustev** [comment] 2016-09-29 10:46
This should be resolved with https://github.com/telerik/kendo-angular2/issues/30

**Closed by ggkrustev** 2016-09-29 10:46 UTC
