### ISSUE TITLE
Tabstrip bug - v0.14.1

### ISSUE THREAD

**Issue by nickcam** [telerik/kendo-angular2#75] opened 2016-11-01 22:07 UTC
Hi Guys, apologies if you're already aware of this. Just upgraded to 0.14.1 of layout module, and clicking to select a tab in the tabstrip no longer works.
I can see it's an error in the template of tabstripComponent.

In this section for generating the tab title list:
```
<li *ngFor=\"let tab of tabs; let i = index;\" (click)=\"selectTab(idx)\"\n 
```
selectTab won't work correctly as `idx` is undefined and is obviously meant to be `i` instead. ie: `(click)=\"selectTab(i)\`.

**Comment by KirilNN** [comment] 2016-11-02 08:08
Hi @nickcam,

We introduced e breaking change in the way the Tabstrip is used with the `0.14` version. Here is a [plunkr](http://plnkr.co/edit/wEBSBPmaLiNtsdqEn1B9?p=preview) that you can edit in order to show the issue that you are facing.

Thanks!

**Comment by KirilNN** [comment] 2016-11-02 08:32
Version `0.14.2` of the package was released, so I will go ahead and close the issue, however feel free to open it again if the problem is still there.

**Closed by KirilNN** 2016-11-02 08:32 UTC

**Comment by nickcam** [comment] 2016-11-02 21:33
Hi @KirilNN, v0.14.2 is working well, thanks. :thumbsup:
