### ISSUE TITLE
ComboBoxComponent giving popup error

### ISSUE THREAD

**Issue by SerDiuK** [telerik/kendo-angular2#34] opened 2016-09-30 07:47 UTC
I've tried installing the ComboBoxComponent but when I press the selector it gives me the following errors related to the popup:

```
EXCEPTION: Error in ./ComboBoxComponent class ComboBoxComponent - inline template:19:8 caused by: kendo_popup_common_1.position is not a function core.

ORIGINAL EXCEPTION: kendo_popup_common_1.position is not a function

Error: Error in ./ComboBoxComponent class ComboBoxComponent - inline template:19:8 caused by: kendo_popup_common_1.position is not a function
```

Any advice on solving this? I can't see any difference between my code and that in the Plunkr.

Additionally, it seems that the ComboBox examples on the documentation website don't function properly either. The search functionality doesn't seem to work, making it no better than a dropdownlist. I don't know if this is a known issue.

**Comment by tapopov** [comment] 2016-09-30 11:46
@SerDiuK, I was unable to reproduce the exception above. Would you mind sharing a Plunkr with the code that led to this error? Regarding the search functionality - indeed, it is not fully implemented at this point, which is something we are working on.

**Comment by SerDiuK** [comment] 2016-10-03 07:41
@tapopov, Thanks for the response and sorry for my late answer. I can't seem to reproduce it on plunkr, nor can I find how to fix it, but I'm guessing it has something to do with the dependencies. I find the documentation confusing on this.

This is my Module file.

`import {NgModule}        from '@angular/core';
import {BrowserModule}   from '@angular/platform-browser';
import {HttpModule}      from "@angular/http";
import {PopupModule}     from '@progress/kendo-angular-popup';
import {DropDownsModule} from '@progress/kendo-angular-dropdowns';

// In memory web-API to fake HTTP calls
import {InMemoryWebApiModule} from "angular-in-memory-web-api/index";
import {InMemoryTreeDataService} from "./services/in-memory-tree-data.service";

import {RolesComponent} from "./roles.component";
import {UserComboboxComponent} from "./user-combobox.component";

@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        PopupModule,
        DropDownsModule,
    ],
    exports: [RolesComponent],
    declarations: [RolesComponent, UserComboboxComponent],
    providers: [CommissionStructureService]
})

export class RolesModule {
}
`

By the way, this is the complete stacktrace:

`core.umd.js:3433 TypeError: kendo_popup_common_1.position is not a function
    at DOMService.position (dom.service.ts:58)
    at AlignService.alignElement (align.service.ts:23)
    at PopupComponent.align (popup.component.ts:192)
    at PopupComponent.ngAfterContentChecked (popup.component.ts:187)
    at DebugAppView._View_ComboBoxComponent1.detectChangesInternal (ComboBoxComponent.ngfactory.js:514)
    at DebugAppView.AppView.detectChanges (core.umd.js:9546)
    at DebugAppView.detectChanges (core.umd.js:9651)
    at DebugAppView.AppView.detectContentChildrenChanges (core.umd.js:9564)
    at DebugAppView._View_ComboBoxComponent0.detectChangesInternal (ComboBoxComponent.ngfactory.js:191)
    at DebugAppView.AppView.detectChanges (core.umd.js:9546)`

**Comment by ggkrustev** [comment] 2016-10-12 08:02
@SerDiuK I don't believe that you need to add the PopupModule, as the DropDownModule already includes it. This is described here:

http://www.telerik.com/kendo-angular-ui/components/dropdowns/

Did you resolve the issue?

**Comment by ggkrustev** [comment] 2016-10-14 07:12
Closing this issue as there is no answer. Please feel free to reopen it, providing more details about the issue.

**Closed by ggkrustev** 2016-10-14 07:12 UTC
