### ISSUE TITLE
Dropdown Popup Alignment Off

### ISSUE THREAD

**Issue by joshNymity** [telerik/kendo-angular2#119] opened 2016-12-06 16:35 UTC
In dropdown version 16.1 the popup dependency was version 11 and everything worked fine.
Now with the new dropdown version 0.18.0 it uses popup version 14.3 which causes this alignment issue.

![screen shot 2016-12-06 at 11 16 23 am](https://cloud.githubusercontent.com/assets/24415153/20934105/01a9f1a8-bba8-11e6-9264-6163773773cd.png)

**Comment by KirilNN** [comment] 2016-12-06 16:44
Can you please provide a demo where the problem can be reproduced? Thanks!

\\cc @ggkrustev

**Comment by AlfredMan** [comment] 2016-12-06 17:40
Hmm, The new dropdownList works well with Kendo's other component, eg inside Kendo's panel 

However, it seems not working with some other custom component.

For demo purpose. I make a very quick custom panel to illustrate how to repeat the bug with this latest update


The following is a very simple panel. If I try to put Kendo's latest dropdownList inside, the same problem described here will show:

Usage of Kendo's dropdownlist inside the simple custom panel. I just used the same example from Kendo's link so I am not going to include the component.ts here for the data. I just simple wrapped this by a <panel-bar></panel-bar> which the entire component with html and style is in the following session.
`
<panel-bar [title]="'test Title'" [open]="true">
<kendo-dropdownlist
[data]="listItems"
[textField]="'text'"
[valueField]="'value'"
>
</kendo-dropdownlist>
</panel-bar>
`

The custom panel bar;
`
@Component({
  selector: 'panel-bar',
  template: `
<div class="panel-header"  (click)="toggle()" >
  <span class="panel-text panel-title">{{title}}</span>
  <div class="button-expand" >{{open?'-':'+'}}</div>
</div>
<div class="panel-block" [@openState]="open?'opened':'closed'" >
  <div class="panel-content can-scroll"> 
    <ng-content ></ng-content>
  </div>
</div>
  `
  style:`
.panel-header{
  display:flex;

  flex-direction:row;
  
  flex-wrap:nowrap;
  
  justify-content:flex-end;

  color:#515967;
  height:40px;

}
.panel-header:hover{
  background-color:#f3f3f4;
  color:black;
}

.panel-text{
  font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;
  text-decoration:none;

}
.panel-title{
  align-self:center;
  
  flex:1;
  
  font-weight: 500;
  zoom:1;    
}
.button-expand{
  align-self:center;
  border:0;

}
.panel-content{
  height:100%;
}
.can-scroll {
  overflow: auto;
  overflow-y: scroll; /* has to be scroll, not auto */
  -webkit-overflow-scrolling: touch;
}

  `
})
export class PanelBarComponent{
  @Input() title:string;
  @Input() open:boolean;

  //private _opened:boolean=false;
  private _hover_color:string="#dbdbde";
  toggle(){
    this.open=!this.open;
  }

}

`

**Comment by ggkrustev** [comment] 2016-12-07 10:55
@AlfredMan, thank you for the posted code snippets. I used them to prepare a pretty simplified version of the PanelBarItem component. It seems that I am missing something, because the DropDownList works as expected:

http://plnkr.co/edit/3z6njnnXlxplFpu6iBR9?p=preview

Could you modify the plunker in order to replicate the issue? This will help us immensely to narrow the problem down and find a solution much faster.

**Comment by AlfredMan** [comment] 2016-12-07 11:45
Hi, I uploaded a sample with the bug here:
http://plnkr.co/edit/HtKc4Q?p=preview

**Comment by ggkrustev** [comment] 2016-12-09 09:36
Hi @AlfredMan,
Thanks for the updated repro demo and please excuse me for the late reply (we were researching the case). It seems that our hosting environment (ui-for-angular site) *doesn't expose the latest Kendo Popup for Angular 2*. That is why I prepared a simple repo that uses the latest popup and it works just fine:

https://github.com/ggkrustev/ng2-test-demo/tree/ddl-in-custom-component
1. Clone the repo (ddl-in-custom-component branch)
2. npm i
3. npm start
(note that the publicURL points to `http://localhost:8080`)

<img width="654" alt="screen shot 2016-12-09 at 11 34 30 am" src="https://cloud.githubusercontent.com/assets/495188/21044221/7f34e6d4-be03-11e6-9872-c30266054e7f.png">

Let me know if I am missing something.

> **NOTE:** We are aware of other positioning issue that will be observed if the anchor (ddl in this case) is positioned additionally, e.g. `text-align: center`. This will be fixed in the next patch version.

**Comment by AlfredMan** [comment] 2016-12-09 11:11
hi

I tried pulling and did the npm i and npm start and launched in port: 8080

This is what I get…. Hmm. I haven’t got time to look inside your code yet. I hope this is just some css error in this repo.

Thanks
Alfred

**Comment by ggkrustev** [comment] 2016-12-12 17:42
@AlfredMan, indeed the demo didn't work, because it was requesting the latest Angular (2.3.x). It, however, has breaking change (multple host bindings are not allowed).

The component works with `~2.2.0` version, which is what I did as a change in the package.json.

With the latest changes in the popup, the dropdownlist works just fine:
![screen shot 2016-12-12 at 7 46 10 pm](https://cloud.githubusercontent.com/assets/495188/21109739/0ca83d08-c0a3-11e6-9b55-633bf273a9c9.png)

>The correct Popup version is 0.14.5

**Comment by ggkrustev** [comment] 2016-12-13 12:01
I will close this as resolved! Please comment if the problem still persists.

**Closed by ggkrustev** 2016-12-13 12:01 UTC
Labels: bug, pkg:dropdowns, pkg:popup
